### ISSUE TITLE
It's April

### ISSUE THREAD

**Issue by jtrmal** [burrmill/burrmill#7]
### I wanted to achieve this:
Try it out

### So I did this:
Visited the github page

### And expected that
It will be available, as it promises it will be available in March

### But actual result was
It wasn't available

### I think that the following info is relevant:
I want!

**Comment by jtrmal** [comment]
Closing, I'm just teasing you.
y.

**Comment by kkm000** [comment]
A day or two more, really! Not all features are in place, but should be usable; finishing the crash course documentation--never thought it would turn out this long. My main concern now is not to leave a user stranded at the point where they would be running billable services not realizing they do.

**Comment by jtrmal** [comment]
No worries. I didn't mean to be annoying.
y.

**Comment by kkm000** [comment]
You weren't! I laughed! I really thought I was ahead of schedule. A little bug here and there, and write a blog--like, everyone uses Wordpress, must be easy. With its WYSIWYG editor, I'm surprised people are able to churn out any blogs at all...

**Comment by jtrmal** [comment]
yeah, if wordpress is wysiwyg, then I'd like to see what the people who are
able to use have inside their head. Actually, I WOULDN'T WANT TO SEE...
y.
